
#define the source locations.  The Salesforce SDK is not a published cocoapod

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first 
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ContactsForce' do
	pod 'SalesforceSDKCore'
	pod 'SalesforceNetwork'
	pod 'SalesforceRestAPI'
end